include:
# Lily58 without dongle
  # Lily58 with oled display(with nice_oled module)
  - board: nice_nano_v2 
    shield: Lily58_left nice_oled
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: Lily58_right nice_oled
    
  # Lily58 with nice!view display(with nice_view_custom module)
  - board: nice_nano_v2
    shield: Lily58_left nice_view_adapter nice_view_custom
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: Lily58_right nice_view_adapter nice_view_custom

#Lily58 with dongle 
  # dongle with LCD display
  - board: nice_nano_v2
    shield: Lily58_dongle_central dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: Lily58_central_dongle
    
  # peripheral with oled display(with nice_oled module)
  - board: nice_nano_v2
    shield: Lily58_dongle_left nice_oled
    artifact-name: Lily58_peripheral_left_oled
  - board: nice_nano_v2
    shield: Lily58_dongle_right nice_oled
    artifact-name: Lily58_peripheral_right_oled
    
  # peripheral with nice!view display(with nice_view_custom module)
  - board: nice_nano_v2
    shield: Lily58_dongle_left nice_view_adapter nice_view_custom
    artifact-name: Lily58_peripheral_left_nice_view
  - board: nice_nano_v2
    shield: Lily58_dongle_right nice_view_adapter nice_view_custom
    artifact-name: Lily58_peripheral_right_nice_view
 
  - board: nice_nano_v2
    shield: settings_reset
