include:
# Corne without dongle
  # Corne with oled display(with nice_oled module)
  - board: nice_nano_v2 
    shield: Corne_left nice_oled
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: Corne_right nice_oled
    
  # Corne with nice!view display(with nice_view_custom module)
  - board: nice_nano_v2
    shield: Corne_left nice_view_adapter nice_view_custom
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: Corne_right nice_view_adapter nice_view_custom

#Corne with dongle 
  # dongle with LCD display
  - board: nice_nano_v2
    shield: Corne_dongle_central dongle_screen
    snippet: studio-rpc-usb-uart
    artifact-name: Corne_central_dongle
    
  # peripheral with oled display(with nice_oled module)
  - board: nice_nano_v2
    shield: Corne_dongle_left nice_oled
    artifact-name: Corne_peripheral_left_oled
  - board: nice_nano_v2
    shield: Corne_dongle_right nice_oled
    artifact-name: Corne_peripheral_right_oled
    
  # peripheral with nice!view display(with nice_view_custom module)
  - board: nice_nano_v2
    shield: Corne_dongle_left nice_view_adapter nice_view_custom
    artifact-name: Corne_peripheral_left_nice_view
  - board: nice_nano_v2
    shield: Corne_dongle_right nice_view_adapter nice_view_custom
    artifact-name: Corne_peripheral_right_nice_view
 
  - board: nice_nano_v2
    shield: settings_reset
